### ISSUE TITLE
what happen?

### ISSUE THREAD

**Issue by jinfeihan57** [flyfishzy/p7zip#207]

**Comment by teoberi** [comment]
Where?

**Comment by teoberi** [comment]
You know flyfishzy(Joe Zhang). He is the owner now!

**Comment by jinfeihan57** [comment]
> 

Actually, I don't know flyfishzy.

**Comment by jinfeihan57** [comment]
> I thought you changed your username, someone had to use your account to transfer the project to another username, there's no other way, this looks bad

Someone logged into my github account. Maybe I logged into my github account on another computer.

**Comment by tansy** [comment]
Write to support. They should be able to assist and help.

**Comment by flyfishzy** [comment]
There were some communication misunderstandings which have been cleared up. The project will be moved to https://github.com/p7zip-project/p7zip
We create an organization so that more people can contribute. 
And @jinfeihan57 will continue to maintain this project.
